HAR-1/Feat/Zuri-Shop-Landing-Page
hngx-org/zuriportfolio-frontend pull request #210
Opened 2023-10-07 21:57 UTC by Mhiracul

## HAR-1/Feat/Zuri-Shop-Landing-Page

> •  Issue ID-#{HAR-1}

# Changes proposed

> Addition : Search functionality, Cart icon from IconsaxOther ,UI improvements
https://github.com/hngx-org/zuriportfolio-frontend/tree/HAR-1/Feat/Zuri-Shop-Landing-Page

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the main branch (left side)
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to

This change allows the application to make requests to the “Fake Store API” for fetching data.

## Screenshots/ Videos

![302ee02e-1539-4832-80d1-98cdfc62bdf7](https://github.com/hngx-org/zuriportfolio-frontend/assets/106194709/8b7baa3f-0436-4537-b7f6-68889f094478)

<img width="1440" alt="Screenshot 2023-10-07 at 22 55 58" src="https://github.com/hngx-org/zuriportfolio-frontend/assets/106194709/0bf08cff-426e-49be-ae91-ebc75519df2e">

#Figma Link
https://www.figma.com/file/xTlU4gv3JqjB3D17mNIErf/Main-Zuri-Design?type=design&node-id=1-5&mode=design

#Hosted Link
https://zuriportfolio-frontend-pw1h.vercel.app/shop

2023-10-07 22:18 UTC, Daniel-Ezekiel commented
Your branch is not up to date with the base branch. Kindly resolve this.

2023-10-07 22:54 UTC, Daniel-Ezekiel commented
Also, you should remove the DS STORE file.

2023-10-07 23:39 UTC, incredible-phoenix246 requested changes
fix conflicts

2023-10-08 04:59 UTC, shalomtaiwo approved these changes

2023-10-08 07:36 UTC, Samadeen approved these changes

2023-10-08 07:37 UTC, merged